[WIP] Disable GraphQL introspection for rails production env
RedHatInsights/sources-api pull request #348
Opened 2021-03-19 12:30 UTC by lpichler

This configuration disable queries described in https://graphql.org/learn/introspection/. 
How this file is described [here](url).
### Links
https://issues.redhat.com/browse/RHCLOUD-11179
**WIP** reason: Depends on

2021-04-05 19:51 UTC, lindgrenj6 approved these changes
LGTM, just waiting on the gem release here: https://github.com/RedHatInsights/insights-api-common-rails/pull/222

2021-04-12 09:30 UTC, lpichler commented
> LGTM, just waiting on the gem release here: [RedHatInsights/insights-api-common-rails#222](https://github.com/RedHatInsights/insights-api-common-rails/pull/222)

@slemrmartin @lindgrenj6  https://github.com/RedHatInsights/insights-api-common-rails/pull/222 is merged.

thanks!

2021-04-13 12:16 UTC, slemrmartin approved these changes

2021-04-13 12:18 UTC, slemrmartin requested changes
Because this PR depends on insights-api-common 5.0.2, Gemfile should define the '>=5.0.2' condition

2021-04-14 13:30 UTC, lpichler commented
> Because this PR depends on insights-api-common 5.0.2, Gemfile should define the '>=5.0.2' condition

done

2021-04-14 16:19 UTC, slemrmartin approved these changes

2021-04-14 16:19 UTC, merged